name: Build Docs
description: Install dependencies and build the Docusaurus documentation

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/python_requirements.txt

    - name: Build docs
      shell: bash
      run: |
        mkdir -p docs/build
        cd docs/build
        cmake ../
        make docusaurus_doc
