name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docs
        uses: ./.github/actions/build-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/docusaurus
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
